spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/testcase
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: TRUE

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        transaction:
          interceptor: TRACE
      hibernate:
        SQL: DEBUG  # 로그를 통해 쿼리 출력
        type:
          descriptor:
            sql: TRACE
        orm:
          jdbc:
            bind: TRACE # 쿼리의 ? 에 실제 바인딩 되는 데이터 로그 출력

mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true  # 언더스코어를 카멜케이스로 바꿔준다.